public class Main {
    public static void main(String[] args) throws Exception {
        Validator.main(new String[] {"Lab1/xml/fitnessClub.xsd", "Lab1/xml/fitnessClub-autogenerated.xsd.xml"});
    }
}